FROM python:3.10-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY pyproject.toml poetry.lock ./

RUN pip install poetry poetry-plugin-export

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src

CMD ["uvicorn", "src.metropolis.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]