version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: metropolis-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=metropolis
      - POSTGRES_PASSWORD=metropolis
      - POSTGRES_DB=metropolis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metropolis -d metropolis_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: metropolis_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  api:
    container_name: metropolis-api
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./prometheus-multiproc-dir:/prometheus_multiproc_dir
    env_file:
      - .env
    environment:
      - prometheus_multiproc_dir=/prometheus_multiproc_dir
      - METROPOLIS_SERVICE_NAME=api
    depends_on:
      - postgres
      - redis
  worker:
    container_name: metropolis-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./src:/app/src
      - ./prometheus-multiproc-dir:/prometheus_multiproc_dir
    env_file:
      - .env
    environment:
      - prometheus_multiproc_dir=/prometheus_multiproc_dir
      - METROPOLIS_SERVICE_NAME=worker
    depends_on:
      - postgres
      - redis
  janitor:
    container_name: metropolis-janitor
    build:
      context: .
      dockerfile: Dockerfile.janitor
    volumes:
      - ./src:/app/src
      - ./prometheus-multiproc-dir:/prometheus_multiproc_dir
    env_file:
      - .env
    environment:
      - prometheus_multiproc_dir=/prometheus_multiproc_dir
      - METROPOLIS_SERVICE_NAME=janitor
    depends_on:
      - postgres
      - redis
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: metropolis-prometheus
    ports:
      - "9090:9090"
    volumes:
      # Mount our prometheus config file
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - api
      
  grafana:
    image: grafana/grafana-oss:9.5.3
    container_name: metropolis-grafana
    ports:
      - "3000:3000"
    volumes:
      # Mount our provisioning files to auto-configure the datasource
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
volumes:
  postgres_data:
      driver: local
           

