"""Add logs column into the job table

Revision ID: 18a9ba45de59
Revises: da1950dc39c6
Create Date: 2025-07-27 15:38:38.533350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a9ba45de59'
down_revision: Union[str, Sequence[str], None] = 'da1950dc39c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'logs')
    # ### end Alembic commands ###
