"""Add retry_count to jobs table

Revision ID: 8d0f3e88d06e
Revises: d08e932e4dd4
Create Date: 2025-07-26 20:10:56.374923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0f3e88d06e'
down_revision: Union[str, Sequence[str], None] = 'd08e932e4dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
